# Generated by Django 5.0.3 on 2024-03-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adults', models.IntegerField(default=0)),
                ('kids', models.IntegerField(default=0)),
                ('toddlers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('boisson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.boisson')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.orders')),
            ],
        ),
        migrations.CreateModel(
            name='table_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Active', max_length=50)),
                ('related_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.orders')),
                ('related_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.tables')),
            ],
        ),
    ]
