# Generated by Django 5.0.2 on 2024-04-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boisson',
            name='prix',
            field=models.FloatField(),
        ),
    ]
