# Generated by Django 5.0.2 on 2024-04-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_boisson_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='boisson',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='boisson',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boissons', to='restaurant.category'),
        ),
    ]
