# Generated by Django 5.0.3 on 2024-03-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prix',
            field=models.IntegerField(null=True),
        ),
    ]
